config/routes.rb
Updater::Application.routes.draw do
  get "upload/update"

  get "home/index"

  resources :sites
  resources :identity, :address

  match '/upload/:identity' => 'upload#update'

  root :to => 'sites#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :address, :identity, :port
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  helper_method :sort_column, :sort_direction

  def index
    @sites = Site.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Site.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def update
	site = Site.find_by_identity(params['identity'])
	site = Site.new unless site
	site.touch
	site.identity = params['identity']
	site.address = request.remote_ip
	site.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def sortable(column, title = nil)
	title ||= column.titleize
	css_class = column == sort_column ? "current #{sort_direction}" : nil
	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	link_to title, {:sort => column, :direction => direction}, {:class => css_class}
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Updater</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identity %><br />
    <%= f.text_field :identity %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.number_field :port %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<%= stylesheet_link_tag "sites" %>
<h1>Listing sites</h1>

<table>
  <tr>
    <th><%= sortable "identity" %></th>
    <th><%= sortable "address" %></th>
    <th><%= sortable "updated_at", "Last Check-In" %></th>
    <th><%= "Port" %></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= link_to site.identity, site %></td>
    <td><%= site.address %></td>
    <td><%= distance_of_time_in_words(Time.now, site.updated_at, true) + " ago" %></td>
    <td><%= site.port %></td>
  </tr>
<% end %>
</table>

<br />

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identity:</b>
  <%= @site.identity %>
</p>

<p>
  <b>Address:</b>
  <%= @site.address %>
</p>

<p>
  <b>Last Updated:</b>
  <%= distance_of_time_in_words(Time.now, @site.updated_at, true) + " ago" %><br>
  <%= @site.updated_at %>
</p>

<p>
	<b>Port Being Tested:</b>
	<%= @site.port %>
</p>


<%= link_to 'Back', sites_path %>

app/views/upload/update.html.erb
<h1>Upload#update</h1>
<p>Find me in app/views/upload/update.html.erb</p>